### ISSUE TITLE
Support for `hdfs:///`

### ISSUE THREAD

**Issue by santosh-d3vpl3x** [Kimahriman/hdfs-native#134]
`hdfs:///` is a valid way of specifying hdfs URL. Especially when `fs.defaultFS` is set. The current implementation, however, doesn't really allow that and we get `URL must contain a host`.

**Comment by Kimahriman** [comment]
Hmm didn't know that was a thing. What happens if you specify `hdfs:///` but your `fs.defaultFS` is `viewfs://myfs`?

**Comment by santosh-d3vpl3x** [comment]
Haven't encountered the situation but technically it should not work unless you have `ViewFsOverloadScheme` configured to `hdfs`.
