### ISSUE TITLE
revise the HdfsError to print more information

### ISSUE THREAD

**Issue by mawenqi** [Kimahriman/hdfs-native#141]
The internal error messages contained in various errors should also be printed out, which means adding {0} in error macro.

As shown in the following code:
```rust
#[derive(Error, Debug)]
pub enum HdfsError {
    #[error("IO error occurred while communicating with HDFS: {0}")]
    IOError(#[from] io::Error),
    #[error("data transfer error: {0}")]
    DataTransferError(String),
    ...
}
```

**Comment by Kimahriman** [comment]
Ah didn't realize that, I've just been debug outputting the errors, will update
