### ISSUE TITLE
Support append

### ISSUE THREAD

**Issue by zuston** [Kimahriman/hdfs-native#43]
Thanks for your great work! Append support will be on the roadmap ? @Kimahriman

**Comment by Kimahriman** [comment]
Wasn't currently on my list but I can try to figure out what it would take. It would add a decent amount of complexity to the write logic because it has to make sure the byte chunk and checksum get lined up properly. If I get time I'll try to wrap my head around how that works in the DFSOutputStream

**Comment by zuston** [comment]
Thanks for your reply. DFSOutputStream is a good example to understand the hood behind of this, let me take a look too.

**Comment by Kimahriman** [comment]
Spent a few minutes seeing if I could understand it. It looks like it might just send a packet with a single chunk of the remaining bytes needed to get to a multiple of the chunk size bytes, and then everything is the same as create. So it might not be as complicated as I thought it might be, let me know if you look at it and think that sounds right

**Comment by zuston** [comment]
> Spent a few minutes seeing if I could understand it. It looks like it might just send a packet with a single chunk of the remaining bytes needed to get to a multiple of the chunk size bytes, and then everything is the same as create. So it might not be as complicated as I thought it might be, let me know if you look at it and think that sounds right

Glad to hear that, append is useful for my intergration with the apache/uniffle.

**Comment by Kimahriman** [comment]
It was simpler than I expected it to be! Let me know if you run into any issues.

**Comment by zuston** [comment]
> It was simpler than I expected it to be! Let me know if you run into any issues.

Thanks, let me take a try
