### ISSUE TITLE
bug: Channel closed while waiting for next ack

### ISSUE THREAD

**Issue by zuston** [Kimahriman/hdfs-native#49]
![image](https://github.com/Kimahriman/hdfs-native/assets/8609142/a5ea2ccc-ddc3-424f-a1eb-73d9f77ffebf)

**Comment by zuston** [comment]
And when using the append, the error logs as follows

![image](https://github.com/Kimahriman/hdfs-native/assets/8609142/30846fc8-95de-4c03-992b-465392800b0e)

**Comment by zuston** [comment]
And the code is here: https://github.com/zuston/incubator-uniffle/blob/hdfs-native/rust/experimental/server/src/store/hdfs.rs

**Comment by Kimahriman** [comment]
Thanks for this, the write path isn't currently very resilient to failures and definitely could use some improvements. I wanted to get a bare minimum write path working, but there's all kinds of situations the DFSOutputStream tries to handle. Some info that would be useful:
- Does this happen deterministically or was this a random error you ran into? 
- Any stats about the size of the file you're appending to or how many replicas.
- What version of Hadoop is this talking to?
- What features does your cluster use? (security, HA namenodes, RBF, etc.)

**Comment by zuston** [comment]
> Does this happen deterministically or was this a random error you ran into?

deterministically

> Any stats about the size of the file you're appending to or how many replicas.

Append to a empty file and 3 replica


we use hadoop 3.2.1 and enable kerberos, HA name ode and RBF

**Comment by Kimahriman** [comment]
> Append to a empty file and 3 replica

What do you mean by append to empty file? Does the file already exist with no size and you open for appending? Or does the file not exist yet?

**Comment by zuston** [comment]
Following the steps
1. using `client.create(file_path, WriteOptions::default()).await?.close().await?;` create a empty file
2. and then append the data into this file.  `self.client.append(file_path).await?.write(data).await?`

**Comment by Kimahriman** [comment]
Can you run with debug rust logs and share the output? It should include all RPC messages being sent with the namenode

**Comment by Kimahriman** [comment]
Actually I took a look at your code again. Is this function: https://github.com/zuston/incubator-uniffle/blob/hdfs-native/rust/experimental/server/src/store/hdfs.rs#L291 missing a close after appending? That would cause the issue you're seeing

**Comment by zuston** [comment]
> https://github.com/zuston/incubator-uniffle/blob/hdfs-native/rust/experimental/server/src/store/hdfs.rs#L291

Oh. yes. I don't close this client.

Do you mean the every append operation should be closed? And is the client thread safe for multiple appending at the same time?

**Comment by Kimahriman** [comment]
> Do you mean the every append operation should be closed? And is the client thread safe for multiple appending at the same time?

`append` opens a writer in append mode. If you keep the writer around you can write to it multiple times, but you need to close it when you're done. There's no way currently to guarantee a read will see the data until you close. 

Not sure exactly what you're asking if it's thread safe. You can't open the same file for append multiple times. You could share a writer across threads behind a mutex

**Comment by zuston** [comment]
> append opens a writer in append mode. If you keep the writer around you can write to it multiple times, but you need to close it when you're done. There's no way currently to guarantee a read will see the data until you close.

Got it.

> Not sure exactly what you're asking if it's thread safe. You can't open the same file for append multiple times. You could share a writer across threads behind a mutex

The client should be shared in multiple threads to use append different files at the same time, right?

**Comment by Kimahriman** [comment]
> The client should be shared in multiple threads to use append different files at the same time, right?

Ah yes that is the case!

**Comment by zuston** [comment]
Thanks @Kimahriman Let me take a try!

**Comment by zuston** [comment]
Now, it works.

**Comment by Kimahriman** [comment]
Awesome! Maybe I'll add a warning if the file writer is dropped without closing

**Comment by zuston** [comment]
> Awesome! Maybe I'll add a warning if the file writer is dropped without closing

Maybe it should close implicitly in drop trait

**Comment by Kimahriman** [comment]
> > Awesome! Maybe I'll add a warning if the file writer is dropped without closing
> 
> Maybe it should close implicitly in drop trait

Yeah that would be nice but it's tricky since it's async. I think the only way would be spawning a fire and forget task without error checking?
