### ISSUE TITLE
Clarify the license

### ISSUE THREAD

**Issue by Xuanwo** [Kimahriman/hdfs-native#50]
Hello, thank you so much for this fantastic project! I'm a member of the [OpenDAL](https://github.com/apache/incubator-opendal) community, and we've been closely following your project for quite some time: https://github.com/apache/incubator-opendal/issues/3144.

The only barrier to integrating your project is the licensing issue. Which license does this project use? Please clarify by including a `LICENSE` file in the repository. I'm happy to create a PR for this if you'd like.

I noticed you've set the `Apache 2.0` license for the Rust crate; does this cover the entire repository?

https://github.com/Kimahriman/hdfs-native/blob/6be6a722da3fc0d952da608476d0f051e5bd1125/rust/Cargo.toml#L11

**Comment by Kimahriman** [comment]
This is my first public project so I'm not terribly familiar with the whole license process, but the whole project should be covered by Apache 2.0. Feel free to make a PR!

**Comment by Xuanwo** [comment]
> This is my first public project so I'm not terribly familiar with the whole license process, but the whole project should be covered by Apache 2.0. Feel free to make a PR!

https://github.com/Kimahriman/hdfs-native/pull/51 has been created. Let's go!
