### ISSUE TITLE
File permission different between `list_status` and `hadoop fs -ls`

### ISSUE THREAD

**Issue by shbhmrzd** [Kimahriman/hdfs-native#57]
Hi, 
I have created a dir and list its permission as below 

```
    let dir_path = "/hdfs-native-test/";
    client.mkdirs(dir_path,  777, true).await.unwrap();

    let file_info = client.get_file_info(dir_path).await.unwrap();
    println!("file status : {:?}", file_info);
```
Output as `file status : FileStatus { path: "/hdfs-native-test/", length: 0, isdir: true, permission: 777, owner: "sraizada", group: "supergroup", modification_time: 1704538751868, access_time: 0 }`

But `hadoop fs -ls /` shows 

```
*$ hadoop fs -ls /
Found 6 items

dr----x--t   - sraizada supergroup          0 2024-01-06 16:29 /hdfs-native-test
```
 I am working on Hadoop 3.2.4
 
 Can you please help with this?
 Thank you!

**Comment by shbhmrzd** [comment]
Also difference across files, from client 
```
file - FileStatus { path: "/sample_file.txt", length: 0, isdir: false, permission: 493, owner: "sraizada", group: "supergroup", modification_time: 1704287676550, access_time: 1704286472844 }
file - FileStatus { path: "/sample_file1.txt", length: 28, isdir: false, permission: 493, owner: "sraizada", group: "supergroup", modification_time: 1704286540867, access_time: 1704286540346 }

```

But cli shows 

```
-rwxr-xr-x   1 sraizada supergroup          0 2024-01-03 18:44 /sample_file.txt
-rwxr-xr-x   1 sraizada supergroup         28 2024-01-03 18:25 /sample_file1.txt
```

Also, what does permission `493` mean?
On searching found a thread with similar issue - https://github.com/ansible/ansible/issues/31952

**Comment by Kimahriman** [comment]
In general this client is still pretty "raw". In this case that means `permission` is an integer value representing the octal permissions, not the string representation of the standard linux permissions. 

If you change your example to 
```rust
client.mkdirs(dir_path,  0o777, true).await.unwrap();
```

it should work as expected. Interpreting the permissions from the file status is a little tricky though. I can try to add some docs and maybe a helper struct to interpret the permissions

**Comment by shbhmrzd** [comment]
Thank you, this helps!
