### ISSUE TITLE
`hdfs_native::Client::new_with_config` cannot be used because the `Configuration` type is not public.

### ISSUE THREAD

**Issue by Xuanwo** [Kimahriman/hdfs-native#65]
![image](https://github.com/Kimahriman/hdfs-native/assets/5351546/7f7dcd0f-641e-458f-ac8e-cedc0dc2497c)

Do you want to expose `Configuration` directly? I'm willing to submit a PR for this.

**Comment by zuston** [comment]
My fault. I want this, feel free to support this.

**Comment by zuston** [comment]
Oh .yes. Feel free to fix this, I hope this could be fixed ASSP.

**Comment by Xuanwo** [comment]
> Ah should have caught that, I assumed rust would have complained internally if that was the case. Lets just have that method take a `HashMap` instead? No reason to really expose the config right now I don't think

Looks nice to me. I will start a PE for this tomorrow.

**Comment by Kimahriman** [comment]
Resolved by https://github.com/Kimahriman/hdfs-native/pull/66
